#+TITLE: Performance tests for QMCkl GPU

*Note* : This branch is for the GPU version of QMCkl only, which can be found [[https://github.com/TREX-CoE/qmckl_gpu][here]] .

* Installation

1. Download and install QMCkl GPU and TREXio
2. Configure the benches :

#+begin_src  bash
./autogen.sh
./configure
#+end_src

You might need some additional flags to configure the build to your liking. Those options are similar to those of QMCkl GPU itself :

- ~--with-qmckl_gpu=...~ : if autoconf doesn't find QMCkl GPU, you need to specify its path. This directory should contain ~lib/~ and ~include/~ subdirectories.
- ~--enable-[omp|acc]~ : by default, benchmarks are built for OpenMP, but the version to build can be explicitely specified.
- ~--disable-autoflags~ : based on the compiler, the configure will try some default flags to enable offload. In case they do not work, you can disable those automatic flags and specify the manually in the ~CFLAGS~ variable.

3. Compile and run them :

#+begin_src  bash
make
./bench_jastrow
#+end_src
